import { firebirdQuery } from '../src/database/firebird/pool.js';
import { applyStoredFirebirdSettings } from '../src/services/settings.service.js';

async function main() {
  await applyStoredFirebirdSettings();
  const ordens = [9696, 9695, 9688];
  const columns = await firebirdQuery(
    `SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS CAMPO,
            F.RDB$FIELD_TYPE AS TIPO, RF.RDB$NULL_FLAG AS NAO_NULO, RF.RDB$DEFAULT_SOURCE AS PADRAO
       FROM RDB$RELATION_FIELDS RF
       JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE
      WHERE RF.RDB$RELATION_NAME IN ('ORDEMSERVICO', 'ITENSORDEMSERVICOPROD', 'ITENSORDEMSERVICOSERV')
      ORDER BY RF.RDB$RELATION_NAME, RF.RDB$FIELD_POSITION`,
  );
  const triggers = await firebirdQuery(
    `SELECT TRIM(RDB$RELATION_NAME) AS TABELA, TRIM(RDB$TRIGGER_NAME) AS NOME,
            RDB$TRIGGER_TYPE AS TIPO, RDB$TRIGGER_INACTIVE AS INATIVO,
            SUBSTRING(RDB$TRIGGER_SOURCE FROM 1 FOR 8191) AS FONTE
       FROM RDB$TRIGGERS
      WHERE RDB$RELATION_NAME IN ('ORDEMSERVICO', 'ITENSORDEMSERVICOPROD', 'ITENSORDEMSERVICOSERV')`,
  );
  const ordensAuditadas = await firebirdQuery(
      `SELECT OS.CHAVE, OS.IDENTIFICADOR, OS.ORDEM, OS.ATIVO, OS.CHAVEEMPRESA, OS.DATA, OS.HORAABERTURA,
              OS.SITUACAO, OS.CHAVECLIFOR, C.CODIGO AS CLIENTE_CODIGO, C.RAZAOSOCIAL,
              OS.CHAVEEQUIPAMENTO, E.CODIGO AS EQUIPAMENTO_CODIGO, E.IDENTIFICACAO,
              OS.CHAVESITUACAOOS, OS.PRIORIDADE, OS.TOTALPRODUTO, OS.TOTALSERVICO, OS.TOTALOS,
              OS.NRODAV, OS.KMATUAL, OS.KMFINAL, OS.CHAVEUSUARIOINICIOU, OS.DATAHORAALT, OS.ORIGEM, OS.CHAVEMOBILE,
              OS.CHAVETABELADESCONTOS, OS.CHAVECFOPOPERFISCAIS, OS.CHAVECFOPPROD, OS.CHAVECFOPSERV,
              OS.CHAVEDOCDESTINO, OS.CHAVETIPOATENDIMENTO, OS.CHAVEPLANOCONTA, OS.CHAVECENTROCUSTO,
              OS.CHAVECTABANCARIA, OS.CHAVEOPERACOESTITULOS, OS.TIPOPAGAMENTO, OS.CHAVECONDPGTO, OS.FORMAPGTO
       FROM ORDEMSERVICO OS
       LEFT JOIN CLIFOR C ON C.CHAVE = OS.CHAVECLIFOR
       LEFT JOIN EQUIPAMENTOS E ON E.CHAVE = OS.CHAVEEQUIPAMENTO
      WHERE OS.CHAVE IN (?, ?, ?)
      ORDER BY OS.CHAVE DESC`,
      ordens,
  );
  const itensProduto = await firebirdQuery(
      `SELECT I.CHAVE, I.CHAVEOS, I.ATIVO, I.CHAVEEMPRESA, I.CHAVEPRODUTO, I.CODPRODUTO,
              I.PRODUTO, I.CHAVEUNIDADE, I.UN, I.QTDE, I.VLRUNIT, I.DESCPORC, I.DESCVLR,
              I.VLRSUBTOTAL, I.VLRTOTAL, I.CHAVETABELAPRECO, I.NUMITEM, I.MOVESTOQUE,
              I.CHAVETRIBUTACAO, I.CHAVECFOP, I.CHAVECFOPOPERFISCAIS, I.PRECOCUSTO,
              I.VLRUNITTABELA, I.VLRVENDAMINIMO, I.CHAVEDPTOESTOQUE, I.NRODAV, I.CHAVEREGRAFISCAL,
              I.TIPOMOVIMENTACAO, I.QTDEESTRESERVADO
         FROM ITENSORDEMSERVICOPROD I
        WHERE I.CHAVEOS IN (?, ?, ?)
        ORDER BY I.CHAVEOS, I.NUMITEM`,
      ordens,
  );
  const itensServico = await firebirdQuery(
      `SELECT I.CHAVE, I.CHAVEOS, I.ATIVO, I.CHAVEEMPRESA, I.CHAVEPRODUTO, I.CODPRODUTO,
              I.PRODUTO, I.CHAVEUNIDADE, I.UN, I.QTDE, I.VLRUNIT, I.DESCPORC, I.DESCVLR,
              I.VLRSUBTOTAL, I.VLRTOTAL, I.CHAVETABELAPRECO, I.NUMITEM,
              I.CHAVECFOP, I.CHAVECFOPOPERFISCAIS, I.PRECOCUSTO, I.VLRUNITTABELA,
              I.VLRVENDAMINIMO, I.NRODAV
         FROM ITENSORDEMSERVICOSERV I
        WHERE I.CHAVEOS IN (?, ?, ?)
        ORDER BY I.CHAVEOS, I.NUMITEM`,
      ordens,
  );
  const referencias = await firebirdQuery(
      `SELECT RC.RDB$RELATION_NAME AS TABELA, RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME,
              RC.RDB$CONSTRAINT_TYPE AS TIPO, SEG.RDB$FIELD_NAME AS CAMPO
         FROM RDB$RELATION_CONSTRAINTS RC
         LEFT JOIN RDB$INDEX_SEGMENTS SEG ON SEG.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
        WHERE RC.RDB$RELATION_NAME IN ('ORDEMSERVICO', 'ITENSORDEMSERVICOPROD', 'ITENSORDEMSERVICOSERV')
        ORDER BY RC.RDB$RELATION_NAME, RC.RDB$CONSTRAINT_NAME, SEG.RDB$FIELD_POSITION`,
  );
  const camposProduto = await firebirdQuery(
    `SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS CAMPO
       FROM RDB$RELATION_FIELDS RF
      WHERE RF.RDB$FIELD_NAME IN (
          'CHAVETRIBUTACAO', 'CHAVECFOP', 'CHAVECFOPOPERFISCAIS',
          'PRECOCUSTO', 'VLRUNITTABELA', 'VLRVENDAMINIMO', 'CHAVEDPTOESTOQUE',
          'CHAVEREGRAFISCAL', 'CHAVETABELAPRECO', 'CHAVECFOPPROD', 'CHAVECFOPSERV'
        )
      ORDER BY RF.RDB$FIELD_NAME, RF.RDB$RELATION_NAME`,
  );
  console.log(JSON.stringify({ camposProduto }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
