import { firebirdQuery } from '../src/database/firebird/pool.js';
import { applyStoredFirebirdSettings } from '../src/services/settings.service.js';

const tabelas = [
  'CLIFOR',
  'ORDEMSERVICO',
  'ITENSORDEMSERVICOPROD',
  'ITENSORDEMSERVICOSERV',
  'CFOPOPERFISCAIS',
  'CFOP',
  'PRODUTOCUSTO',
  'PRODUTOVENDA',
  'PRODUTODPTOESTOQUE',
  'ESTOQUE',
  'DPTOESTOQUEEMPUSUPERFIL',
];

async function main() {
  await applyStoredFirebirdSettings();
  const columns = await firebirdQuery(
    `SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA,
            TRIM(RF.RDB$FIELD_NAME) AS CAMPO,
            F.RDB$FIELD_TYPE AS TIPO,
            F.RDB$FIELD_SUB_TYPE AS SUBTIPO,
            F.RDB$FIELD_SCALE AS ESCALA,
            RF.RDB$NULL_FLAG AS NAO_NULO
       FROM RDB$RELATION_FIELDS RF
       JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE
      WHERE RF.RDB$RELATION_NAME IN (${tabelas.map(() => '?').join(', ')})
      ORDER BY RF.RDB$RELATION_NAME, RF.RDB$FIELD_POSITION`,
    tabelas,
  );
  const clientes = await firebirdQuery(
    `SELECT CHAVE, CODIGO, CHAVETABELAPRECO, CHAVECONDPGTO
       FROM CLIFOR
      WHERE CODIGO IN (?, ?)`,
    ['000001', '000432'],
  );
  const catalogo = await firebirdQuery(
    `SELECT P.CHAVE, P.CODIGO, P.CHAVEUNIDADE,
            PC.PRECOCUSTO,
            PV.CHAVETABELAPRECO, PV.PRECOVENDA, PV.PRECOVENDAMINIMO,
            PDE.CHAVEDPTOESTOQUE, PDE.SALDO
       FROM PRODUTO P
       LEFT JOIN PRODUTOCUSTO PC
         ON PC.CHAVEPRODUTO = P.CHAVE AND PC.CHAVEEMPRESA = 1 AND PC.ATIVO = 1
       LEFT JOIN PRODUTOVENDA PV
         ON PV.CHAVEPRODUTO = P.CHAVE AND PV.CHAVEEMPRESA = 1 AND PV.CHAVETABELAPRECO = 1 AND PV.ATIVO = 1
       LEFT JOIN PRODUTODPTOESTOQUE PDE
         ON PDE.CHAVEPRODUTO = P.CHAVE AND PDE.CHAVEEMPRESA = 1 AND PDE.ATIVO = 1
      WHERE P.CODIGO IN (?, ?, ?)
      ORDER BY P.CODIGO, PDE.CHAVEDPTOESTOQUE`,
    ['001234', '001258', '000348'],
  );
  const perfis = await firebirdQuery(
    `SELECT P.CHAVE, P.CODIGO, P.DESCRICAO, P.CHAVETRIBUTACAO, P.CHAVECFOPPRODDE, P.CHAVECFOPSERVDE,
            P.MOVESTOQUE, P.MOVESTOQUEPROPRIA, P.TIPOMOVIMENTACAO,
            CP.CODIGO AS CFOP_PROD_CODIGO, CS.CODIGO AS CFOP_SERV_CODIGO
       FROM CFOPOPERFISCAIS P
       LEFT JOIN CFOP CP ON CP.CHAVE = P.CHAVECFOPPRODDE
       LEFT JOIN CFOP CS ON CS.CHAVE = P.CHAVECFOPSERVDE
      WHERE P.CHAVEEMPRESA = 1 AND P.ATIVO = 1
      ORDER BY P.CHAVE`,
  );
  const camposFiscaisProduto = await firebirdQuery(
    `SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS CAMPO
       FROM RDB$RELATION_FIELDS RF
      WHERE RF.RDB$RELATION_NAME = 'PRODUTO'
        AND (
          RF.RDB$FIELD_NAME CONTAINING 'TRIB' OR
          RF.RDB$FIELD_NAME CONTAINING 'FISC' OR
          RF.RDB$FIELD_NAME CONTAINING 'GRUPO'
        )
      ORDER BY RF.RDB$FIELD_POSITION`,
  );
  const tabelasFiscais = await firebirdQuery(
    `SELECT TRIM(RDB$RELATION_NAME) AS TABELA
       FROM RDB$RELATIONS
      WHERE RDB$SYSTEM_FLAG = 0
        AND (RDB$RELATION_NAME CONTAINING 'TRIBUT' OR RDB$RELATION_NAME CONTAINING 'FISCAL')
      ORDER BY RDB$RELATION_NAME`,
  );
  const produtoFiscal = await firebirdQuery(
    `SELECT P.CHAVE, P.CODIGO, P.CHAVEGRUPOFISCAL, P.CHAVEGRUPOFISCALPF,
            GF.CHAVETRIBUTACAO, GF.CHAVECFOPOPERFISCAIS
       FROM PRODUTO P
       LEFT JOIN GRUPOFISCAL GF ON GF.CHAVE = P.CHAVEGRUPOFISCAL
      WHERE P.CODIGO IN (?, ?, ?)
      ORDER BY P.CODIGO`,
    ['001234', '001258', '000348'],
  );
  const camposGrupoFiscal = await firebirdQuery(
    `SELECT TRIM(RF.RDB$FIELD_NAME) AS CAMPO
       FROM RDB$RELATION_FIELDS RF
      WHERE RF.RDB$RELATION_NAME = 'GRUPOFISCAL'
      ORDER BY RF.RDB$FIELD_POSITION`,
  );
  const perfisPadrao = await firebirdQuery(
    `SELECT CHAVE, CODIGO, DESCRICAO, OPERFISCPRINCIPALDOC, STATUS,
            CHAVECFOPPRODDE, CHAVECFOPSERVDE
       FROM CFOPOPERFISCAIS
      WHERE CHAVEEMPRESA = 1 AND ATIVO = 1
      ORDER BY CHAVE`,
  );
  const tabelasDav = await firebirdQuery(
    `SELECT TRIM(RDB$RELATION_NAME) AS TABELA
       FROM RDB$RELATIONS
      WHERE RDB$SYSTEM_FLAG = 0 AND RDB$RELATION_NAME CONTAINING 'DAV'
      ORDER BY RDB$RELATION_NAME`,
  );
  const camposPadraoUsuario = await firebirdQuery(
    `SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS CAMPO
       FROM RDB$RELATION_FIELDS RF
      WHERE RF.RDB$RELATION_NAME IN ('TABELAPRECOEMPUSUPERFIL', 'DPTOESTOQUEEMPUSUPERFIL')
      ORDER BY RF.RDB$RELATION_NAME, RF.RDB$FIELD_POSITION`,
  );
  console.log(JSON.stringify({ camposPadraoUsuario }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
